### ISSUE TITLE
how to use it in got project?

### ISSUE THREAD

**Issue by shuiRong** [fengkx/got-iconv#64]
Is there any Getting Started information?

**Comment by fengkx** [comment]
You can find examples in [test cases](https://github.com/fengkx/got-iconv/blob/master/test/gbk.js) Just replace got with this package.

But I no longer use got in my personal project any more https://github.com/fengkx/NodeRSSBot/issues/574, beacuse I found it seems to be buggy in a high request frequency  situation (at least for got@12 when I am using it) https://github.com/fengkx/NodeRSSBot/issues/353 and doesn't support commonjs.

I think make-fetch-happen is a good choice, because it is battle tested by npm and support `res.textConverted()`  which is literally what got-iconv do.
